# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Set the working directory in the container to /app
WORKDIR /app

# Add the current directory contents into the container at /app
ADD . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir psycopg2-binary
RUN pip install --no-cache-dir Werkzeug==3.0.3
RUN pip install --no-cache-dir Flask==3.0.3
RUN pip install --no-cache-dir requests==2.32.3
RUN pip install --no-cache-dir Flask-Cors==4.0.1
RUN pip install --no-cache-dir Flask-Login==0.6.3
RUN pip install --no-cache-dir flask-restx==1.3.0


# Make port 8888 available to the world outside this container
EXPOSE 8888

# Run app.py when the container launches
CMD ["python", "main.py"]