version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_fva
    ports:
      - "5432:5432"
      - "8888:8888"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=postgres