# Use an official PostgreSQL image
FROM postgres:13.2-alpine

# Set the environment variable for the database password
ENV POSTGRES_PASSWORD test

# Set the environment variable for the database name
ENV POSTGRES_DB postgres

# Set the environment variable for the database user
ENV POSTGRES_USER test

# Expose the PostgreSQL port
EXPOSE 5432